# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'voicechanger_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_voicechanger(object):
    def setupUi(self, form_voicechanger):
        form_voicechanger.setObjectName("form_voicechanger")
        form_voicechanger.resize(1000, 700)
        form_voicechanger.setMinimumSize(QtCore.QSize(1000, 700))
        form_voicechanger.setMaximumSize(QtCore.QSize(1000, 700))
        form_voicechanger.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lb_visualizer = QtWidgets.QLabel(form_voicechanger)
        self.lb_visualizer.setGeometry(QtCore.QRect(20, 15, 71, 16))
        self.lb_visualizer.setObjectName("lb_visualizer")
        self.gv_visualizer_input = QtWidgets.QGraphicsView(form_voicechanger)
        self.gv_visualizer_input.setGeometry(QtCore.QRect(10, 35, 980, 275))
        self.gv_visualizer_input.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.gv_visualizer_input.setLineWidth(0)
        self.gv_visualizer_input.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gv_visualizer_input.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gv_visualizer_input.setObjectName("gv_visualizer_input")
        self.pb_record = QtWidgets.QPushButton(form_voicechanger)
        self.pb_record.setGeometry(QtCore.QRect(350, 650, 110, 32))
        self.pb_record.setObjectName("pb_record")
        self.pb_play = QtWidgets.QPushButton(form_voicechanger)
        self.pb_play.setEnabled(False)
        self.pb_play.setGeometry(QtCore.QRect(540, 650, 110, 32))
        self.pb_play.setObjectName("pb_play")
        self.hs_frequency = QtWidgets.QSlider(form_voicechanger)
        self.hs_frequency.setEnabled(False)
        self.hs_frequency.setGeometry(QtCore.QRect(10, 630, 160, 22))
        self.hs_frequency.setOrientation(QtCore.Qt.Horizontal)
        self.hs_frequency.setObjectName("hs_frequency")
        self.lb_frequency = QtWidgets.QLabel(form_voicechanger)
        self.lb_frequency.setGeometry(QtCore.QRect(20, 610, 71, 16))
        self.lb_frequency.setObjectName("lb_frequency")
        self.gv_visualizer_output = QtWidgets.QGraphicsView(form_voicechanger)
        self.gv_visualizer_output.setGeometry(QtCore.QRect(10, 320, 980, 275))
        self.gv_visualizer_output.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.gv_visualizer_output.setLineWidth(0)
        self.gv_visualizer_output.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gv_visualizer_output.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gv_visualizer_output.setObjectName("gv_visualizer_output")

        self.retranslateUi(form_voicechanger)
        QtCore.QMetaObject.connectSlotsByName(form_voicechanger)

    def retranslateUi(self, form_voicechanger):
        _translate = QtCore.QCoreApplication.translate
        form_voicechanger.setWindowTitle(_translate("form_voicechanger", "VoiceChanger"))
        self.lb_visualizer.setText(_translate("form_voicechanger", "Visualizer:"))
        self.pb_record.setText(_translate("form_voicechanger", "Record"))
        self.pb_play.setText(_translate("form_voicechanger", "Play"))
        self.lb_frequency.setText(_translate("form_voicechanger", "Frequency:"))
